# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ('-date_of_creation',)},
        ),
        migrations.AlterField(
            model_name='box',
            name='date_of_creation',
            field=models.DateTimeField(verbose_name='date of creation'),
        ),
    ]
